[project]
name = "music-airflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-airflow==3.1.3",
    "apache-airflow-providers-fab",
    "polars>=1.36.1",
    "requests>=2.32.5",
]
